services:
  - type: web
    name: sertifikat-bot
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py  # gunicorn ni olib tashladik
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "123456789"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: certificates-data
      mountPath: /opt/render/project/src/certificates
      sizeGB: 1
